# Generated by Django 5.2.6 on 2025-09-14 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderproduct",
            old_name="orden",
            new_name="order",
        ),
    ]
