# Generated by Django 5.2.6 on 2025-09-12 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="nombre",
            new_name="name",
        ),
    ]
